dist: trusty

language: elixir

matrix:
  include:
    - elixir: 1.7.4
      otp_release: 21.1

cache:
  directories:
    - deps
    - _build

script:
  - MIX_ENV=test mix do deps.get, deps.compile, coveralls.travis